### ISSUE TITLE
license問題討論

### ISSUE THREAD

**Issue by ghost** [fosstp/drupal4school#13]
目前採用GPLv3授權，
但ibm db2 driver license應該不相容GPLv3，
另ibm db2 driver能否包在docker image裡散佈，
應該在正式release前確認處理方式。

另外 theme/Accessibility 這個theme是GPLv2也不相容GPLv3
所以整個project不能用GPLv3 license,

最後萬一不能包進docker image的話，
要改用什麼方式處理？

**Comment by leejoneshane** [comment]
GPLv3 授權是指我們的專案授權，至於 IBM DB2 官方網站宣稱：
You can download and install the IBM Data Server Driver for ODBC and CLI and use it with your ODBC and CLI applications without a special license.（來源http://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0024162.html?cp=SSEPEK_11.0.0）
theme/Accessiblity 是我開發的，改用 GPLv3 黨然也可以。

至於由誰提供，這個問題比較複雜，如果我們在版權聲明中，寫清楚其餘包含套件應遵守原開發團隊的授權方式，這樣是否可以解決問題。

**Comment by williamwu0220** [comment]
小弟對授權相關的議題蠻有興趣的，於是針對這個議題我也寫信去問了對於自由軟體相關授權有研究的法律顧問，剛剛收到回信，全文照貼如下，請參考：

> 吳老師您好，
> 
> 沒錯，您的顧慮是對的，事實上依照這份授權說明(International Program License Agreement)，IBM Data Server Driver Package僅提供予他的商業簽約客戶使用，非商業簽約客戶其實並非授權對象，一般來說整套完整的IBM Data Server Driver Package，是在商業散布時以DVD光碟的方式提供給客戶，或者在客戶在向IBM註冊帳號之後，也可以在輸入客戶帳號與密碼後下載取得：https://www-01.ibm.com/marketing/iwm/iwm/web/preLogin.do?source=swg-idsdpds
> 
> 我將International Program License Agreement這份授權契約的要點條列如下：
> 
> 1、IBM grants Licensee a nonexclusive license to 1) use the Program up to the Authorized Use specified in the PoE, 2) make and install copies to support such Authorized Use, and 3) make a backup copy, all provided that
> 
> 合法被授權者必須持有認證文件(Proof of Entitlement, PoE)才可以使用，然後在契約的核可範圍去安裝使用，若是備份亦僅基於保存之目的，得自行備份一份，在原程式損壞之後才可以啟用備份版。
> 
> 2、Licensee may transfer the Program and all of Licensee’s license rights and obligations to another party only if that party agrees to the terms of this Agreement. If the license is terminated for any reason by either party, Licensee is prohibited from transferring the Program to another party. Licensee may not transfer a portion of 1) the Program or 2) the Program’s Authorized Use. When Licensee transfers the Program, Licensee must also transfer a hard copy of this Agreement, including the LI and PoE. Immediately after the transfer, Licensee’s license terminates.
> 
> IBM Data Server Driver Package的商業授權是可以移轉的，例如甲和IBM取得授權，之後持此IBM Data Server Driver Package幫客戶乙安裝使用環境，之後甲可以將IBM Data Server Driver Package整份商業授權移交給客戶乙，但當移交完成後，甲自己即失去IBM Data Server Driver Package的授權地位，不能再行使用。也就是說，International Program License Agreement一次只對一個商業用戶生效。
> 
> 所以小結論是，較嚴縝的處理方式，不在GitHub直接提供IBM Data Server Driver Package的程式源碼，會較為穩當。
> 
> 細部一點來說，IBM Data Server Driver Package這整個資料庫伺服器的驅動安裝包，是採商業授權International Program License Agreement的方式來向客戶提供，但它裡面有用到不少的自由開源軟體，所以它透過「dsdriver_notices.txt」這個檔案，將這些自由開源軟體列為第三方軟體(third party code)，述明其原本的授權說明，但整體的IBM Data Server Driver Package，是採用自己的商業授權模式來提供利用，故您所看到的這些文件，其實就是International Program License Agreement這個商業授權文件在不同語言下的表達。
> 
> cs_CZ.iso88592    adjust performance  23 days ago
> cs_CZ.utf8    adjust performance  23 days ago
> de_DE.iso88591    adjust performance  23 days ago
> de_DE.utf8    adjust performance  23 days ago
> el_GR.iso88597    adjust performance  23 days ago
> el_GR.utf8    adjust performance  23 days ago
> en_US.iso88591    adjust performance  23 days ago
> ………
> 
> drupal4school這套程式，整體而言還是可以採自由開源軟體的方式釋出，不論是使用GPL-2.0或GPL-3.0，但就IBM Data Server Driver Package的部份，建議以文字說明導向IBM原廠的下載連結即可，意思就是，若要完全還原使用環境，使用者必須自行取得IBM Data Server Driver Package的商業授權版本，來配合drupal4school使用，這樣的方式較不會有後續的糾紛。
> 
> 若有進一步的想法或疑問，我們隨時聯繫討論。
> 
> 日安、健康！
> 
> :)
> 
> 20161005 14:39 開放文化基金會 林誠夏

**Comment by leejoneshane** [comment]
這件事我有一些不同看法：
首先我們提供的並非 IBM Data Server Driver Package 而是  IBM Data Server Driver for ODBC and CLI，按照官方的授權文件（請參考前文的連結），授權條款僅要求該驅動程式所連結的伺服器，必須是有【適當的授權】。表列中的 DB2® Database for Linux®, UNIX®, and Windows® 就包含各校目前所安裝的 IBM DB2 Express-C，官方網站聲明是 【IBM® DB2® Express-C is the free edition of DB2—free to develop, free to deploy, free to distribute. 】（來源：https://www.ibm.com/developerworks/downloads/im/db2express/），所以【適當的授權】在我們的案例裡並沒有疑慮。

目前我擔心的是：在整份 IBM Data Server Driver for ODBC and CLI 授權文件中，完全沒有提到是否可以散布，然而 IBM Data Server Driver for ODBC and CLI 並未包含在 IBM DB2 Express-C 之中的，所以也無法比照 IBM DB2 Express-C 自由散布。

如果必須到 IBM 網站下載，就必須先註冊帳號，然後每次登入都會取得一個暫時的 token 來下載，這整個過程無法用程式代理，也就是說 image 無法自動 Build。

**Comment by williamwu0220** [comment]
說明一下，我提供給顧問的 license 內容，是 drupal4school ibm 目錄下的 license 檔案。整包是不是 ibm 有另外的授權我不清楚，但是以 https://github.com/fosstp/drupal4school/tree/master/ibm/dsdriver/license 這裡的授權文件來看，仍然是和法律顧問提到的事情是相同的

**Comment by scrazy77** [comment]
所以我們用的是這個嗎？
https://www-304.ibm.com/support/docview.wss?uid=swg21418043

> Why use it?
> The driver has a much smaller footprint than the IBM Data Server Client and the IBM Data Server Runtime Client.
> You can have multiple installations of the driver on a single machine.
> You can install the driver on a machine that already has an IBM Data Server Client installed.
> **You can include the driver in your database application installation package, and redistribute the driver with your applications. Under certain conditions, you can redistribute the driver with your database applications royalty-free.
> The driver can reside on an NFS mounted file system.**

**Comment by scrazy77** [comment]
> Who Uses it? 
> The IBM Data Server Driver for ODBC and CLI is a lightweight deployment solution designed for independent software vendors (ISV) deployments. 

可是我們算是 ISV嗎？(應該不算？)

**Comment by williamwu0220** [comment]
Update: 可忽略此篇，請看我下方回覆

根據樓上 @scrazy 的連結，有提到

You can install the driver on a machine that already has an IBM Data Server Client installed. 

所以代表這個 IBM Data Server Driver for ODBC and CLI 相依於 IBM Data Server Client？

那 d4s 有包 IBM Data Server Client 嗎？

**Comment by williamwu0220** [comment]
我們算 ISV 嗎？如果照顧問的說法應該不算，因為沒簽合約之類的？我猜可以申請，只是申請的條件與是否會過就不知道了…

**Comment by scrazy77** [comment]
剛丟了ibm的form去問了，不知有沒有成功，再等看看...

**Comment by williamwu0220** [comment]
研究了一下，以下是目前的心得與想法，有錯請指正：
1. 根據 http://www.ibm.com/support/knowledgecenter/zh-tw/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.install.doc/doc/c0023452.html 的說法，看起來 IBM Data Server Driver for ODBC and CLI 是可以獨立安裝，不用相依 IBM 其他套件
2. 根據 @leejoneshane 老師前面的連結，如果是 ISV 即可散佈  IBM Data Server Driver for ODBC and CLI 套件
3. 看起來 drupal4school/ibm/dsdriver 這是一整包的安裝包，但其下又有 license 授權說明，對照法律顧問的意見，意思應該就是你必須是 ISV 才可散佈，或是個人用戶自己註冊帳密下載，這和第 2 點相呼應
4. drupal4school/ibm/dsdriver 這目錄看起來不單單只是 ODBC 與 CLI，還包含其他語言的驅動，所以這個目錄應該就是所謂的 IBM Data Server Driver Package？其中 installDSDriver 就是把所有的驅動全部裝進去，只是 d4s 只用到了其中一部分的 driver。但不管如何，既然該目錄下有 license 授權說明，應該還是以這裡的宣告為主？

現在看起來就是等 IBM 回覆了...

**Comment by williamwu0220** [comment]
剛跑去 IBM 直接下載  IBM Data Server Driver Package 和 IBM Data Server Driver for ODBC and CLI 安裝檔下來比對，確認 drupal4school/ibm/dsdriver 是前者，因為後者整個目錄結構與授權說明都不一樣

**Comment by leejoneshane** [comment]
當初下載 IBM Data Server Driver Package 是因為它裡面包含各種不同 Linux 版本的 IBM Data Server Driver for ODBC and CLI，我們的確只使用其中的 ODBC 和 CLI 用來編譯 php-db2 函式庫。

現在看 DB2 Express-C database server 的授權合約，來源：http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-STAG-A7PUBL&title=DB2%20Express-C%20database%20server ，把 IBM Data Server Driver Package 和 IBM Data Server Driver for ODBC and CLI 同列為「支援程式」，同時說：
f. 若被授權人取得之本「程式」為「支援程式」，被授權人僅得利用本「程式」支援「主要程式」，並受「主要程式」授權條款之拘束

主程式授權條款 e. 則提到：
e. 除本合約明文許可外，被授權人不得：(1) 使用、複製、修改或散布本「程式」

但是在他的官網上面，又說可以免費使用、複製、散布，這就看不懂了！

**Comment by scrazy77** [comment]
我們是裝 https://pecl.php.net/package/ibm_db2 吧？
可是我看 pecl ibm_db2 的source完全沒有odbc部份說....
從 http://php.net/manual/en/ibm-db2.installation.php 來看，
下面有個comment 在pecl 安裝 ibm_db2時，需要下載 dsd並安裝才能work...

**Comment by leejoneshane** [comment]
pecl  的 IBM DB2 套件是透過 CLI 存取資料庫沒錯，另外也可以用 PDO 物件透過 unixodbc 存取資料庫。這兩個部分合起來就是 IBM Data Server Driver for ODBC and CLI。

由於 drupal 核心直接繼承 PDO 物件，所以將來也可以改用 PDO 以便取得較好的系統支援。

**Comment by scrazy77** [comment]
這樣看來不能散佈的可能性比較高了，所以需要相關模組的可能只能自行download，然後我們寫script協助後續安裝吧

**Comment by scrazy77** [comment]
剛下載 純"IBM Data Server Driver for ODBC and CLI" 解開來試裝 pecl ibm_db2，結果因為沒有include file無法安裝

```
checking for IBM_DB2 support... yes, shared
checking PHP... Detected 64-bit PHP
checking IBM_DB_HOME location... not found
checking Looking for DB2 CLI libraries... checking      in /opt/ibm/dsdriver...
checking      in /opt/ibm/dsdriver/lib64...
checking      in /opt/ibm/dsdriver/lib... found
checking for DB2 CLI include files in default path... checking in /opt/ibm/dsdriver... not found
configure: error: Please reinstall the DB2 CLI distribution
```

**Comment by leejoneshane** [comment]
還是要學全誼直接提供編譯好的 so 檔，刪掉源碼。這樣可行嗎？

**Comment by scrazy77** [comment]
只有so檔 沒裝 dsd能動嗎？

**Comment by leejoneshane** [comment]
好像只要能找到 libdb2.so 就可以執行，不知道 IBM Data Server Driver for ODBC and CLI 裡面有沒有。

**Comment by scrazy77** [comment]
裡面有，可是抽出來應該違反license了，全誼的作法是怎樣呢？

**Comment by liao-chianan** [comment]
全誼的作法是弄一片ALLE.ISO，裝完甚麼都有了，至於license......

**Comment by leejoneshane** [comment]
如果提供 IBM Data Server Driver for ODBC and CLI 加上編譯好的 ibm_db2.so 呢？

**Comment by scrazy77** [comment]
> 如果提供 IBM Data Server Driver for ODBC and CLI 加上編譯好的 ibm_db2.so 呢？

還在跟ibm聯繫中，得要確認 我們能包 " IBM Data Server Driver for ODBC and CLI"才行

**Comment by scrazy77** [comment]
目前進度：
IBM業務還要進一步諮詢相關人員後回覆。
