### ISSUE TITLE
啟用d4s_bootstrap 為預設theme會跳error

### ISSUE THREAD

**Issue by liao-chianan** [fosstp/drupal4school#15]
初步看應該是theme所需要的feature與module沒有進來

**Comment by sp19851985** [comment]
應該是母版型沒放進來，所以error，這個的母版型應該是bootstrap

**Comment by sp19851985** [comment]
另外，我的版型也叫d4s_bootstrap，那....是改我的版型名稱和內容嗎？

**Comment by leejoneshane** [comment]
我看你的 github 版型專案中有 bootstrap_d4s_wonderland.info，該檔名就是你的版型名稱。這個版型的相依模組非常多，而且有些模組還需要額外 libraries，目前這些 libraries 還未採用 composer 管理機制，要安裝升級都只能手動，所以暫時不考慮包進來！

另外相依模組 d4s_bootstrap_features，在語系翻譯上有一些不符合 drupal 規範需要更改。舉例來說，t() 函式是用來把英文字串對應成各種語系的字串，因此理論上只接受英文為引數，但在該模組裡很多地方有用到中文，例如：t('中文') 這樣意思變成是把 '中文' 這個字串翻譯成中文，這就很奇怪了！

**Comment by leejoneshane** [comment]
目前的版本 d4s_bootstrap 已經不會再報錯，但首頁外觀看起來好像還缺些什麼？

**Comment by sp19851985** [comment]
永銘老師的d4s_bootstrap應該也有一些相依模組和libraries要包進去，否則也會無法顯示出正確的版型。

**Comment by sp19851985** [comment]
我的版型本來也叫d4s_bootstrap，bootstrap_d4s_wonderland.info是我昨天才改的。而d4s_bootstrap_features是為了把內建的views和區塊都包進去才另外嘗試的方法，但那模組的函式我倒是沒仔細去研究，如果無法符合規範，那這版型我就暫時不繼續動工了，等發表會完再慢慢改。

**Comment by liao-chianan** [comment]
我目前還在測試中，個人覺得全部都測試完後沒有問題，我們再包進去，雖然可能趕不上研習，但穩定總是比較好一點
