### ISSUE TITLE
docker run Syntax error on line 74 of /etc/apache2/apache2.conf

### ISSUE THREAD

**Issue by scrazy77** [fosstp/drupal4school#7]
Status: Downloaded newer image for fosstp/drupal:latest
[Fri Sep 09 07:56:11.608827 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_LOCK_DIR} is not defined
[Fri Sep 09 07:56:11.608897 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_PID_FILE} is not defined
[Fri Sep 09 07:56:11.608903 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_RUN_USER} is not defined
[Fri Sep 09 07:56:11.608905 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_RUN_GROUP} is not defined
[Fri Sep 09 07:56:11.608922 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Fri Sep 09 07:56:11.621231 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Fri Sep 09 07:56:11.621535 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Fri Sep 09 07:56:11.621550 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
AH00526: Syntax error on line 74 of /etc/apache2/apache2.conf:
Invalid Mutex directory in argument file:${APACHE_LOCK_DIR}

**Comment by leejoneshane** [comment]
fixed already in the new version.
